### PR TITLE
Adds online spaces to CoC

### PR DESCRIPTION
**Pull request by LKHennessy**
Online spaces included in CoC as discussed in15/03/16 committee meeting.

### CODE REVIEW

**Comment by pat** [comment]
Might want to change the underlying markdown file as well :)

**Comment by MelissaKaulfuss** [comment]
👍

**Comment by sevenseacat** [comment]
Right - this HTML file gets rebuilt from the markdown files every time we deploy the site. 

The markdown file for the CoC is located in `pages/code-of-conduct.html.md`

**Comment by LKHennessy** [comment]
Ahhhh. Damn it! Ok that makes sense. I changed the md and force pushed.
Should I undo the html changes?

**Comment by LKHennessy** [comment]
I guess if it gets rebuilt it doesn't really matter either way.

**Comment by sevenseacat** [comment]
it's all good, I jumped the gun it seems :)

**Comment by pat** [comment]
Sorry Lauren! I'd missed that you'd added the markdown change as well. Just merged this into master, and then deployed it to the `gh-pages` branch. It's now live :)

**Comment by LKHennessy** [comment]
Thanks Pat! I had forgotten about this!

**Pull request merged**
