### PR TITLE
2015 Developer Survey

### PR DESCRIPTION
**Pull request by joho**
I'm pushing this up in a very early state to make it easier to concurrently gather feedback on a few elements 

## Background

Step one on increasing the remit of rubyaustralia and doing more industry/academic outreach on behalf of aussie ruby devs is to get a solid picture of who that community/industry is.

For now the immediate objectives in having this data is to speak to the validity of ruby as a commercial development option, to help prosecute the case for universities spitting out ruby devs and for individual employers to understand there's a rich, stable ecosystem in the Australian market.

I'd hope we can do a survey every year, and that future surveys can have a slightly less commercial bent (just ask the right questions to get a good year to year diff). Many big thanks to Liam Esler who helped draft the survey based on his experience representing Australia's indie game dev scene.

## Desired Feedback

Visit http://goo.gl/forms/h0yyUgJwdW to see what's in the survey

* Any suggestions on question wording or better options for select fields
* can someone please give me a reasonable industry list to put in there?

I'll post as follow up comments on PR for other feedback needed further along. Would be best if we can keep all feedback on this PR in the interest of transparency.

## Rollout Plan
- [x] Create campaign monitor list for survey respondents
- [x] Finalise Survey
- [x] Finalise intro/landing page
- [x] Wipe pre-release entries in spreadsheet (from testing etc)
- [ ] merge this PR & deploy
- [ ] Mail roro list
- [ ] Post in relevant slack communites (viewsource et al)
- [ ] Tweet from rubyau and ask for many retweets etc

### CODE REVIEW

**Comment by benaskins** [comment]
Looks good @joho - you might want to add 'Director/Owner' to the employment status options.

**Comment by joho** [comment]
@benaskins done, thanks!

**Comment by benaskins** [comment]
No dramas. I had a little poke around for industry lists and found this -http://www.aigroup.com.au/portal/site/aig/workplacerelations/awardmodernisation/industrieslist/ - it's a little unwieldy but might be a good place to whittle down from.

**Comment by MelissaKaulfuss** [comment]
This makes things complex but I'd recommend thinking about how the gender question is phrased – Could be simply "I identify my gender as"

(http://itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-question-on-an-application-form-more-inclusive/)

**Comment by pat** [comment]
Just ran through the survey, only thing I noted was that VISA should just be visa (we're not referring to the brand). Also, do we want to extend it to cover tools and such (e.g. which versions of Ruby do people use), ala Hapton Catlin's Ruby Survey - which we could possibly steal questions from: http://www.askr.me/ruby

Granted, that's got the potential to skew the survey away beyond its original purpose, so I'm not sure whether such questions would be a good move.

**Comment by joho** [comment]
@MelissaKaulfuss amended to "What's your gender identity?"

@pat fixed the VISA thing, I think I got autocorrected somewhere along the line. I think the tooling question is interesting but pretty big scope creep. Intuitively I don't expect that our community's tooling will vary much from the general population, and the amount of questions we'd need to add to meaningfully compare AU ruby use vs world ruby use would make the survey pretty unwieldy.

@benaskins I've added "Director/Owner". WRT to industries: I just read that list - I'm not even sure how I'd whittle it down :-D

**Comment by joho** [comment]
For industry list I'm inclined to use the top level categories from https://developers.google.com/adwords/api/docs/appendix/productsservices?hl=en which works out to be
```
Apparel
Arts & Entertainment
Beauty & Personal Care
Business & Industrial
Computers & Consumer Electronics
Dining & Nightlife
Family & Community
Finance
Food & Groceries
Health
Hobbies & Leisure
Home & Garden
Internet & Telecom
Jobs & Education
Law & Government
News
Occasions & Gifts
Real Estate
Retailers & General Merchandise
Sports & Fitness
Travel & Tourism
Vehicles
```
They're a bit vague but `¯\_(⊙︿⊙)_/¯`

**Comment by joho** [comment]
OK, I've fleshed out the landing page for the survey. Would appreciate proper review of the page now. I'll commit a compiled version of the page once everyone's OK with copy etc.

Because of my upcoming travel timetable I'll need to finalise feedback before noon saturday with the aim to start publishing saturday afternoon some time. That's not to say it has to go out this week, but if there are no outstanding objections by then I'll take it as tacit approval :wink:

**Comment by joho** [comment]
OK, industry list is in, and I've committed a built version of the page. I _think_ this is good to go.

**Comment by pat** [comment]
@joho just added you as a collaborator on this repo, so you can deploy when you like :) (details on how to do that are in the README)

**Comment by evolve2k** [comment]
Hi peeps

Since Im on this list I thought Id throw in my 2 cents, great work on this
by the way John and co :)


1. Education

Just had a quick look, noticed that there's no accounting for if you did
not finish high school and it's a required question.
Maybe can you add an "*other*" or "*didn't need formal education*", "*n/a*"
or something like that.


2. Income

Knowing just the gross income without a sense of if they are working full
time or what % of full time will make analysis harder later.
In my situation I'm actually studying half time currently so my income is
down.
You ask for income but don't get a sense if people are working full time or
part-time or casually, what you really want to be able to calc later is
peoples collective FTE (Full Time Equivilent Rate).
My hypothesis is that as ruby coding generally pays well there is more
people that cut back their hours.

I would add something like:

*What % of a standard full time working load are you undertaking in a usual
week currently.*
(Full time being calculated at 38 hours/week)



3. Community question

I know we want to minimize questions but would it also be worth asking a
postioning question to see if people are involved in the national ruby
community.

*Have you attended a Ruby Conf or Rails Camp in the last 2 years?*

Could be very helpful to see if the survey is getting out beyond the usual
crowd and also to get a sense of how large the pool is and what % of devs
that answer it that aren't active in the community.



Richie

**Comment by joho** [comment]
@evolve2k thanks for the feedback!

1. I'll add other to education
2. In the earlier question about work status i differentiate between full-time & part-time which I can use as a filter on the data.
3. That's a good question, I'll add it next to the "did you even know ruby au was a thing" question

**Pull request merged**
